#!/usr/bin/env python3
"""Create a local .env without echoing API keys."""

from __future__ import annotations

import argparse
import getpass
from pathlib import Path


def ask(label: str, *, secret: bool = False, default: str = "") -> str:
    suffix = f" [{default}]" if default else ""
    value = (getpass.getpass(f"{label}{suffix}: ") if secret else input(f"{label}{suffix}: ")).strip()
    return value or default


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--force", action="store_true", help="replace an existing .env")
    args = parser.parse_args()
    env_path = Path(".env")
    if env_path.exists() and not args.force:
        raise SystemExit(".env already exists; use --force only when you intend to replace it")

    provider = ask("Default provider (openai/qwen/seedream)", default="openai").lower()
    if provider not in {"openai", "qwen", "seedream"}:
        raise SystemExit("provider must be openai, qwen, or seedream")
    openai_key = ask("Optional OpenAI API key", secret=True)
    small_key = ask("Optional GPT Image 2 <=1K key", secret=True)
    qwen_key = ask("Optional Qwen/DashScope key", secret=True)
    seedream_key = ask("Optional Seedream/Ark key", secret=True)
    required = {"openai": openai_key, "qwen": qwen_key, "seedream": seedream_key}[provider]
    if not required:
        raise SystemExit(f"{provider} API key is required for the selected default provider")
    model = {
        "openai": "gpt-image-2",
        "qwen": "qwen-image-2.0-pro",
        "seedream": "doubao-seedream-4-0-250828",
    }[provider]

    lines = [
        "# Generated by scripts/setup.py; keep this file out of version control.",
        f"OPENAI_API_KEY={openai_key}",
        f"OPENAI_API_KEY_1K={small_key}",
        "IMAGE_1K_MAX_EDGE=1024",
        f"IMAGE_MODEL={model}",
        f"QWEN_API_KEY={qwen_key}",
        "QWEN_IMAGE_MODEL=qwen-image-2.0-pro",
        f"SEEDREAM_API_KEY={seedream_key}",
        "SEEDREAM_IMAGE_MODEL=doubao-seedream-4-0-250828",
        "SERVICE_API_KEY=",
        "API_RATE_LIMIT_PER_MINUTE=30",
        "MCP_DNS_REBINDING_PROTECTION=true",
        "MCP_ALLOWED_HOSTS=localhost:*,127.0.0.1:*,image-gen.xinlanzi.com,image-gen.xinlanzi.com:*",
        "MCP_ALLOWED_ORIGINS=",
        "MCP_MAX_REQUEST_BODY_BYTES=73400320",
        "OSS_ENABLED=false",
    ]
    env_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Wrote {env_path.resolve()}; configured providers without displaying secrets.")


if __name__ == "__main__":
    main()
